version: '2' 

services:
  
  docdel-db:
    image: postgres

  docdel-web:
    build: docdel/

    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - ./docdel:/myapp
    ports:
      - "3002:3000"
    depends_on:
      - docdel-db

  auth-db:
    image: postgres

  auth-web:
    build: findit-auth/
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - ./findit-auth/:/myapp
    ports:
      - "3001:3000"
    depends_on:
      - auth-db

  findit-solr:
    build: "https://github.com/dtulibrary/solr_with_fixtures.git"

  findit-db:
    image: postgres

  findit-web:
    build: toshokan/
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - ./toshokan/:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - findit-solr
      - findit-db

  sendit-db:
    image: postgres

  sendit-web:
    build: sendit/
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - ./sendit/:/myapp
    ports:
      - "3004:3000"
    depends_on:
      - sendit-db

  covers-db:
    image: postgres

  covers-web:
    build: covers/
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - ./covers/:/myapp
    ports:
      - "3008:3000"
    depends_on:
        - covers-db

  getit-web:
    build: getit/
    command: rackup
    volumes:
      - ./getit/:/myapp
    ports:
      - "3003:9292"

  docstore-db:
    image: postgres

  docstore-web:
    build: docstore/
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - ./docstore:/myapp
    ports:
      - "3005:3000"
    depends_on:
      - docstore-db
        
  alerting-db:
    image: postgres

  alerting-web:
    build: alerting/
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - ./alerting:/myapp
    ports:
      - "3007:3000"
    depends_on:
      - alerting-db
