version: '2' 

services:

  db:
    build: db/

  docdel:
    build: docdel/

    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - ./docdel:/myapp
    ports:
      - "3002:3000"
    depends_on:
      - db

  findit-auth:
    build: findit-auth/
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - ./findit-auth/:/myapp
    ports:
      - "3001:3000"
    depends_on:
      - db

  findit-solr:
    ports:
      - "8983:8983"
    build: "https://github.com/dtulibrary/solr_with_fixtures.git"


  findit:
    build: toshokan/
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - ./toshokan/:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - findit-solr
      - db

  sendit:
    build: sendit/
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - ./sendit/:/myapp
    ports:
      - "3004:3000"
    depends_on:
      - db

  covers:
    build: covers/
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - ./covers/:/myapp
    ports:
      - "3008:3000"
    depends_on:
      - db

  getit:
    build: getit/
    command: thin start -p 3000
    volumes:
      - ./getit/:/myapp
    ports:
      - "3003:3000"

  docstore:
    build: docstore/
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - ./docstore:/myapp
    ports:
      - "3005:3000"
    depends_on:
      - db
        
  alerting:
    build: alerting/
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - ./alerting:/myapp
    ports:
      - "3007:3000"
    depends_on:
      - db

  cas:
    build: rubycas-server/
    command: bundle exec rubycas-server -c config.yml
    #volumes:
    #  - ./rubycas-server:/myapp
    ports:
      - "3012:3000"
    depends_on:
      - db

  redmine:
    build: redmine/
    ports: 
      - "3006:3000"

  freecite:
    build: freecite/
    command: rackup --host 0.0.0.0 --port 3000
    volumes:
      - ./freecite/:/myapp
    ports:
      - "3013:3000"

# uses built in sqlite3 at the moment

